goods view commit- by 정&지
sowon-dev/bestPriceMarket pull request #2
Opened 2020-10-24 16:16 UTC by jekk0215

상품 등록, 수정, 상세, 목록 전체적인 뷰는 만들고 
뷰 연결도 했습니다.

2020-10-24 18:03 UTC, sowon-dev requested changes
안녕하세요~
아래 두가지 파일에서 conflicts 이나서요~
```
.classpath
target/m2e-wtp/web-resources/META-INF/MANIFEST.MF
```

resolve conflicts 버튼 클릭하면 차이점 확인할 수 있는데 일부러 코드 수정하신건가요? 확인부탁드려요

2020-10-25 01:08 UTC, jekk0215 commented
일부러 수정한 파일들은 아니에요!
저도 왜 저런 코드들이 생겨났는지 모르겠네요,,
구글에 찾아봐도 잘 안 나오네요 ㅠㅠ

2020-10-25 02:24 UTC, sowon-dev commented
네 그럼  main 브랜치에 있는 내용으로 해주시면 좋을것같아요. 컨플릭 제거해주세요~ 그 후 머지할게요!

2020-10-25 03:01 UTC, jekk0215 commented
넵 수정 했습니다~~!

2020-10-25 03:04 UTC, sowon-dev reviewed
LGTM

2020-10-25 03:07 UTC, sowon-dev approved these changes

2020-10-25 03:10 UTC, sowon-dev approved these changes

2020-10-25 03:24 UTC, closed without merging